---
- name: Enable EPEL if CentOS
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no
  when: ansible_distribution == 'CentOS'

- name: Install nginx
  package:
    name: nginx
    state: present

- name: Enable and start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
