---
- name: Enable EPEL if CentOS
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no
  when: ansible_distribution == 'CentOS'

- name: Install nginx
  package:
    name: nginx
    state: present

- name: Enable and start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Install goss on remote
  shell:
    cmd: "curl -fsSL https://goss.rocks/install | sh"
  args:
    warn: false

- name: Copy goss file
  copy:
    src: "{{ role_path }}/tests/goss_tests.yaml"
    dest: /root/goss_tests.yaml

- name: Test goss file
  local_action: goss
  args:
    path: "/root/goss_tests.yaml"
